In [1]:
import sys
from pathlib import Path
BASE_DIR = Path.cwd()
SYNTHERGENT_DIR = BASE_DIR / 'src' 
sys.path.insert(-2, str(SYNTHERGENT_DIR))
from synthergent.util import *
from synthergent.constants import *

WARNING 03-29 13:05:22 _custom_ops.py:20] Failed to import from vllm._C with ModuleNotFoundError("No module named 'vllm._C'")
INFO 03-29 13:05:22 importing.py:15] Triton not installed or not compatible; certain GPU-related functions will not be available.

ModuleNotFoundError: No module named 'synthergent.cleaner.Sample'

In [1]:
Dataset.of()

NameError: name 'Dataset' is not defined

In [ ]:
import sys
from pathlib import Path
HOME_DIR = Path.cwd()
SYNTHERGENT_DIR = HOME_DIR / 'src' 
sys.path.insert(-2, str(SYNTHERGENT_DIR))

from pprint import pprint
import ray
import copy, json, yaml, os, io, gzip, bz2, lzma, ray, gc, glob
os.environ['DISABLE_DEFAULT_TRACKER'] = 'True'
import dask.dataframe as dd
import pandas as pd
from ray.util.dask import ray_dask_get, enable_dask_on_ray, disable_dask_on_ray
from bokeh.palettes import viridis
from synthergent.util import *
from synthergent.constants import *

import hvplot.pandas
import holoviews as hv
import plotly.express as px
import plotly.io as pio
from IPython.display import display
from bokeh.palettes import Spectral, Set2, Set3

pio.templates.default = 'plotly_white'
hvplot.extension('bokeh')
# hvplot.extension('plotly')

pio.renderers.default='iframe'

In [2]:
ray.shutdown()
ray.init(
    _temp_dir=FileMetadata.of(os.path.expanduser('~/ray/')).mkdir(),
    ignore_reinit_error=True,
)

2024-12-14 19:17:12,101	INFO worker.py:1715 -- Started a local Ray instance. View the dashboard at http://127.0.0.1:8265

RayContext(dashboard_url='127.0.0.1:8265', python_version='3.11.8', ray_version='2.9.2', ray_commit='fce7a361807580953364e2da964f9498f3123bf9', protocol_version=None)

(raylet) [2024-12-14 19:17:21,030 E 34524 31882454] (raylet) file_system_monitor.cc:111: /Users/adivekar/ray/session_2024-12-14_19-17-08_969545_34460 is over 95% full, available space: 19491704832; capacity: 494384795648. Object creation will fail if spilling is required.
(raylet) [2024-12-14 19:17:31,093 E 34524 31882454] (raylet) file_system_monitor.cc:111: /Users/adivekar/ray/session_2024-12-14_19-17-08_969545_34460 is over 95% full, available space: 19491172352; capacity: 494384795648. Object creation will fail if spilling is required.
(raylet) [2024-12-14 19:17:41,180 E 34524 31882454] (raylet) file_system_monitor.cc:111: /Users/adivekar/ray/session_2024-12-14_19-17-08_969545_34460 is over 95% full, available space: 19490766848; capacity: 494384795648. Object creation will fail if spilling is required.
(raylet) [2024-12-14 19:17:51,278 E 34524 31882454] (raylet) file_system_monitor.cc:111: /Users/adivekar/ray/session_2024-12-14_19-17-08_969545_34460 is over 95% full, available space: 19489738752; capacity: 494384795648. Object creation will fail if spilling is required.
(raylet) [2024-12-14 19:18:01,306 E 34524 31882454] (raylet) file_system_monitor.cc:111: /Users/adivekar/ray/session_2024-12-14_19-17-08_969545_34460 is over 95% full, available space: 19489419264; capacity: 494384795648. Object creation will fail if spilling is required.
(raylet) [2024-12-14 19:18:11,369 E 34524 31882454] (raylet) file_system_monitor.cc:111: /Users/adivekar/ray/session_2024-12-14_19-17-08_969545_34460 is over 95% full, available space: 19487555584; capacity: 494384795648. Object creation will fail if spilling is required.
(raylet) [2024-12-14 19:18:21,417 E 34524 31882454] (raylet) file_system_monitor.cc:111: /Users/adivekar/ray/session_2024-12-14_19-17-08_969545_34460 is over 95% full, available space: 19488665600; capacity: 494384795648. Object creation will fail if spilling is required.
(raylet) [2024-12-14 19:18:31,468 E 34524 31882454] (raylet) file_system_monitor.cc:111: /Users/adivekar/ray/session_2024-12-14_19-17-08_969545_34460 is over 95% full, available space: 19488649216; capacity: 494384795648. Object creation will fail if spilling is required.
(raylet) [2024-12-14 19:18:41,545 E 34524 31882454] (raylet) file_system_monitor.cc:111: /Users/adivekar/ray/session_2024-12-14_19-17-08_969545_34460 is over 95% full, available space: 19487354880; capacity: 494384795648. Object creation will fail if spilling is required.
(raylet) [2024-12-14 19:18:51,591 E 34524 31882454] (raylet) file_system_monitor.cc:111: /Users/adivekar/ray/session_2024-12-14_19-17-08_969545_34460 is over 95% full, available space: 19487342592; capacity: 494384795648. Object creation will fail if spilling is required.
(raylet) [2024-12-14 19:19:01,673 E 34524 31882454] (raylet) file_system_monitor.cc:111: /Users/adivekar/ray/session_2024-12-14_19-17-08_969545_34460 is over 95% full, available space: 19487285248; capacity: 494384795648. Object creation will fail if spilling is required.
(raylet) [2024-12-14 19:19:11,685 E 34524 31882454] (raylet) file_system_monitor.cc:111: /Users/adivekar/ray/session_2024-12-14_19-17-08_969545_34460 is over 95% full, available space: 19487092736; capacity: 494384795648. Object creation will fail if spilling is required.
(raylet) [2024-12-14 19:19:21,692 E 34524 31882454] (raylet) file_system_monitor.cc:111: /Users/adivekar/ray/session_2024-12-14_19-17-08_969545_34460 is over 95% full, available space: 19486978048; capacity: 494384795648. Object creation will fail if spilling is required.
(raylet) [2024-12-14 19:19:31,770 E 34524 31882454] (raylet) file_system_monitor.cc:111: /Users/adivekar/ray/session_2024-12-14_19-17-08_969545_34460 is over 95% full, available space: 19486744576; capacity: 494384795648. Object creation will fail if spilling is required.

In [3]:
from synthergent import Synthergent, Cleaner
import cleaners  ## Importing these registers all the cleaners

In [4]:
Cleaner.subclasses()

{cleaners.AddLol}

In [6]:
class AddLol(Cleaner):
    class Params(Cleaner.Params):
        reps: int = 1
        col: str = 'generations'
    
    def clean(
            self,
            data: pd.DataFrame,
    ) -> pd.DataFrame:
        for _ in range(self.params.reps):
            data[self.params.col] = data[self.params.col].astype(str) + ' lol'
        return data

In [7]:
addlol_chain = Synthergent.of(
    Cleaner.of('AddLol', params={}),
    Cleaner.of('AddLol', params={}),
    Cleaner.of('AddLol', params={}),
    Cleaner.of('AddLol', params={}),
    Cleaner.of('AddLol', params={}),
    Cleaner.of('AddLol', params={}),
)

In [8]:
_data = pd.DataFrame([
    dict(idx=idx, generations='ha')
    for idx in range(int(1e6))
])

In [9]:
! rm -rf /Users/adivekar/ray/lol/*

zsh:1: no matches found: /Users/adivekar/ray/lol/*

In [11]:
addlol_chain(
    data=_data,
    scaling='processes',
    max_workers=5,
    save=dict(path='~/ray/lol/', format='parquet'),
    verbosity=1,
)

Synthergent:   0%|          | 0/6 [00:00<?, ?step/s]

Process SpawnProcess-7:
Traceback (most recent call last):
Process SpawnProcess-9:
Traceback (most recent call last):
Process SpawnProcess-6:
  File "/Users/adivekar/miniconda3/envs/synthesizrr/lib/python3.11/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/Users/adivekar/miniconda3/envs/synthesizrr/lib/python3.11/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/adivekar/miniconda3/envs/synthesizrr/lib/python3.11/concurrent/futures/process.py", line 249, in _process_worker
    call_item = call_queue.get(block=True)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/adivekar/miniconda3/envs/synthesizrr/lib/python3.11/multiprocessing/queues.py", line 122, in get
    return _ForkingPickler.loads(res)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: Can't get attribute 'AddLol' on <module '__main__' (built-in)>
  File "/Users/adivekar/miniconda3/envs/synthesizrr/lib/python3.11/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/Users/adivekar/miniconda3/envs/synthesizrr/lib/python3.11/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/adivekar/miniconda3/envs/synthesizrr/lib/python3.11/concurrent/futures/process.py", line 249, in _process_worker
    call_item = call_queue.get(block=True)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/adivekar/miniconda3/envs/synthesizrr/lib/python3.11/multiprocessing/queues.py", line 122, in get
    return _ForkingPickler.loads(res)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: Can't get attribute 'AddLol' on <module '__main__' (built-in)>
Traceback (most recent call last):
Process SpawnProcess-8:
  File "/Users/adivekar/miniconda3/envs/synthesizrr/lib/python3.11/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/Users/adivekar/miniconda3/envs/synthesizrr/lib/python3.11/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/adivekar/miniconda3/envs/synthesizrr/lib/python3.11/concurrent/futures/process.py", line 249, in _process_worker
    call_item = call_queue.get(block=True)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/adivekar/miniconda3/envs/synthesizrr/lib/python3.11/multiprocessing/queues.py", line 122, in get
    return _ForkingPickler.loads(res)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: Can't get attribute 'AddLol' on <module '__main__' (built-in)>
Traceback (most recent call last):
Process SpawnProcess-10:
  File "/Users/adivekar/miniconda3/envs/synthesizrr/lib/python3.11/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/Users/adivekar/miniconda3/envs/synthesizrr/lib/python3.11/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/adivekar/miniconda3/envs/synthesizrr/lib/python3.11/concurrent/futures/process.py", line 249, in _process_worker
    call_item = call_queue.get(block=True)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/adivekar/miniconda3/envs/synthesizrr/lib/python3.11/multiprocessing/queues.py", line 122, in get
    return _ForkingPickler.loads(res)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: Can't get attribute 'AddLol' on <module '__main__' (built-in)>
Traceback (most recent call last):
  File "/Users/adivekar/miniconda3/envs/synthesizrr/lib/python3.11/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/Users/adivekar/miniconda3/envs/synthesizrr/lib/python3.11/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/adivekar/miniconda3/envs/synthesizrr/lib/python3.11/concurrent/futures/process.py", line 249, in _process_worker
    call_item = call_queue.get(block=True)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/adivekar/miniconda3/envs/synthesizrr/lib/python3.11/multiprocessing/queues.py", line 122, in get
    return _ForkingPickler.loads(res)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: Can't get attribute 'AddLol' on <module '__main__' (built-in)>

Error in Synthergent:
[ERROR]: BrokenProcessPool: "A process in the process pool was terminated abruptly while the future was running or pending."
Traceback:
	/Users/adivekar/workplace/synthesizrr/src/synthergent/base/framework/chain/Chain.py line 391, in _execute_chain...
	/Users/adivekar/workplace/synthesizrr/src/synthergent/base/framework/chain/Chain.py line 557, in _execute_step...
	/Users/adivekar/workplace/synthesizrr/src/synthergent/base/framework/chain/Chain.py line 530, in _execute_step...
	pydantic/decorator.py line 40, in pydantic.decorator.validate_arguments.validate.wrapper_function...
	pydantic/decorator.py line 134, in pydantic.decorator.ValidatedFunction.call...
	pydantic/decorator.py line 206, in pydantic.decorator.ValidatedFunction.execute...
	/Users/adivekar/workplace/synthesizrr/src/synthergent/base/util/language.py line 593, in wrapper...
	/Users/adivekar/workplace/synthesizrr/src/synthergent/Cleaner.py line 85, in run...
	/Users/adivekar/workplace/synthesizrr/src/synthergent/Cleaner.py line 162, in _clean_local...
	/Users/adivekar/workplace/synthesizrr/src/synthergent/base/util/concurrency.py line 944, in accumulate...
	/Users/adivekar/workplace/synthesizrr/src/synthergent/base/util/concurrency.py line 1001, in accumulate...
	/Users/adivekar/workplace/synthesizrr/src/synthergent/base/util/concurrency.py line 828, in get_result...
	/Users/adivekar/miniconda3/envs/synthesizrr/lib/python3.11/concurrent/futures/_base.py line 449, in result...
	/Users/adivekar/miniconda3/envs/synthesizrr/lib/python3.11/concurrent/futures/_base.py line 401, in __get_result...

AttributeError: 'NoneType' object has no attribute 'pop'

In [10]:
Reader.of('parquet').read('/Users/adivekar/ray/lol/')['idx'].nunique()

Read 0 row(s):   0%|          | 0/334 [00:00<?, ?file/s]

10000000

In [9]:
! rm -rf /Users/adivekar/ray/lol/*

zsh:1: no matches found: /Users/adivekar/ray/lol/*

In [12]:
addlol_chain(
    data=_data,
    scaling='processes',
    max_workers=1,
    save=dict(path='~/ray/lol/', format='parquet'),
)

Synthergent:   0%|          | 0/6 [00:00<?, ?step/s]

Saved to: "/Users/adivekar/ray/lol/"

In [13]:
Reader.of('parquet').read('/Users/adivekar/ray/lol/')['idx'].nunique()

Read 0 row(s):   0%|          | 0/334 [00:00<?, ?file/s]

10000000

In [ ]:
import sys
from pathlib import Path
HOME_DIR = Path.home()
SYNTHERGENT_DIR = HOME_DIR / 'workplace' / 'synthesizrr' / 'src' 
sys.path.insert(-2, str(SYNTHERGENT_DIR))

from pprint import pprint
import ray
import copy, json, yaml, os, io, gzip, bz2, lzma, ray, gc, glob
os.environ['DISABLE_DEFAULT_TRACKER'] = 'True'
import dask.dataframe as dd
import pandas as pd
from ray.util.dask import ray_dask_get, enable_dask_on_ray, disable_dask_on_ray
from bokeh.palettes import viridis
from synthergent.base.util import *
from synthergent.base.data import *
from synthergent.base.metric.classification_metrics import *
from synthergent.base.framework import *
from synthergent.base.framework.task.classification import _normalize_label
import synthergent.base.algorithm

import hvplot.pandas
import holoviews as hv
import plotly.express as px
import plotly.io as pio
from IPython.display import display
from bokeh.palettes import Spectral, Set2, Set3

pio.templates.default = 'plotly_white'
hvplot.extension('bokeh')
# hvplot.extension('plotly')

pio.renderers.default='iframe'


from synthergent import Synthergent, Cleaner
import cleaners  ## Importing these registers all the cleaners

/var/folders/0b/h2z5fys10h5cxlgh2tqf1y840000gr/T/ipykernel_16005/1974000823.py:11: DeprecationWarning: The current Dask DataFrame implementation is deprecated.
In a future release, Dask DataFrame will use new implementation that
contains several improvements including a logical query planning.
The user-facing DataFrame API will remain unchanged.

The new implementation is already available and can be enabled by
installing the dask-expr library:

    $ pip install dask-expr

and turning the query planning option on:

    >>> import dask
    >>> dask.config.set({'dataframe.query-planning': True})
    >>> import dask.dataframe as dd

API documentation for the new implementation is available at
https://docs.dask.org/en/stable/dask-expr-api.html

Any feedback can be reported on the Dask issue tracker
https://github.com/dask/dask/issues

  import dask.dataframe as dd

In [3]:
# # # logging.getLogger('concurrent.futures').setLevel(logging.CRITICAL + 1)



# @contextmanager
# def suppress_IgnoreSystemExitFilter():
#     # Instantiate the filter
#     filter_instance = IgnoreSystemExitFilter()

#     filter_instance = IgnoreSystemExitFilter()
#     # logger = logging.getLogger()
#     logger = logging.getLogger('concurrent.futures')
#     logger.addFilter(filter_instance)
    
#     try:
#         # Yield control back to the context block
#         yield
#     finally:
#         # Remove the filter upon exiting the context
#         logger.removeFilter(filter_instance)

In [4]:
# # logging.getLogger('concurrent.futures').setLevel(logging.CRITICAL + 1)

# class IgnoreThreadKillExceptionFilter(logging.Filter):
#     def filter(self, record):
#         if record.exc_info:
#             exc_type = record.exc_info[0]
#             if issubclass(exc_type, ThreadKillException):
#                 return False
#         return True

# @contextmanager
# def suppress_ThreadKillException():
#     # Instantiate the filter
#     filter_instance = IgnoreThreadKillExceptionFilter()
    
#     root_logger = logging.getLogger()
    
#     # Add the filter to the root logger
#     root_logger.addFilter(filter_instance)
    
#     try:
#         # Yield control back to the context block
#         yield
#     finally:
#         # Remove the filter upon exiting the context
#         time.sleep(1)
#         root_logger.removeFilter(filter_instance)

# # # Get the 'concurrent.futures' logger
# # logger = logging.getLogger('concurrent.futures')

# # # Add the custom filter to ignore SystemExit exceptions
# # logger.addFilter(IgnoreThreadKillExceptionFilter())

In [5]:
executor = dispatch_executor(parallelize='threads', max_workers=3)
def worker(wid):
    for step_i in range(1):
        print(f"Worker{wid} running step {step_i}...")
        time.sleep(0.1)

for _ in range(10):
    executor.submit(worker, _)

stop_executor(executor)

Worker0 running step 0...
Worker1 running step 0...
Worker2 running step 0...
Worker3 running step 0...
Worker4 running step 0...
Worker5 running step 0...
Worker6 running step 0...
Worker7 running step 0...
Worker8 running step 0...

In [6]:
executor = dispatch_executor(parallelize='threads', max_workers=3)
def worker(wid):
    for step_i in range(1):
        print(f"Worker{wid} running step {step_i}...")
        time.sleep(0.1)

for _ in range(10):
    executor.submit(worker, _)

time.sleep(0.3)

stop_executor(executor)
# time.sleep(5)
# _logger.removeFilter(_filter_instance)

Worker0 running step 0...Worker1 running step 0...
Worker2 running step 0...

Worker3 running step 0...
Worker4 running step 0...
Worker5 running step 0...
Worker6 running step 0...Worker7 running step 0...
Worker8 running step 0...

Worker9 running step 0...

In [10]:
# Example usage in a thread
def thread_function():
    # Your thread code that might raise exceptions
    raise ValueError('123')

thread = threading.Thread(target=thread_function)
thread.start()
thread.join()

Exception in thread Thread-8 (thread_function):
Traceback (most recent call last):
  File "/Users/adivekar/miniconda3/envs/synthesizrr/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "/Users/adivekar/miniconda3/envs/synthesizrr/lib/python3.11/site-packages/ipykernel/ipkernel.py", line 766, in run_closure
    _threading_Thread_run(self)
  File "/Users/adivekar/miniconda3/envs/synthesizrr/lib/python3.11/threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "/var/folders/0b/h2z5fys10h5cxlgh2tqf1y840000gr/T/ipykernel_16005/1735755490.py", line 4, in thread_function
ValueError: 123

In [8]:
# ipykernel_logger = logging.getLogger('ipykernel.ipkernel')

# # Add the filter to the logger
# ipykernel_logger.addFilter(ThreadKilledSystemExceptionFilter())

In [9]:
# Example: Create and terminate a thread
def worker():
    for _ in range(20):
        print("Worker running...")
        time.sleep(0.5)

# Create a thread
t = threading.Thread(target=worker)
t.start()

# Let the thread run for a while
time.sleep(1.5)

# Kill the thread
kill_thread(t.ident)

# Wait for the thread to terminate
t.join()

Worker running...
Worker running...
Worker running...

Exception in thread Thread-7 (worker):
Traceback (most recent call last):
  File "/Users/adivekar/miniconda3/envs/synthesizrr/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "/Users/adivekar/miniconda3/envs/synthesizrr/lib/python3.11/site-packages/ipykernel/ipkernel.py", line 766, in run_closure
    _threading_Thread_run(self)
  File "/Users/adivekar/miniconda3/envs/synthesizrr/lib/python3.11/threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "/var/folders/0b/h2z5fys10h5cxlgh2tqf1y840000gr/T/ipykernel_16005/2706909532.py", line 5, in worker
synthergent.base.util.concurrency.ThreadKilledSystemException

In [11]:
def worker():
    # try:
    while True:
        print("Worker is running...")
        time.sleep(1)
    # except ThreadKilledSystemException:
    #     print("Worker received ThreadKilledSystemException and is terminating.")

# Start the worker thread using ThreadPoolExecutor or directly
thread = threading.Thread(target=worker)
thread.start()

time.sleep(3)  # Let the worker run for a bit

# Get the thread ID
tid = ctypes.c_long(thread.ident)

# Forcefully raise the custom exception in the worker thread
ctypes.pythonapi.PyThreadState_SetAsyncExc(tid, ctypes.py_object(ThreadKilledSystemException))

# Wait for the thread to terminate
thread.join()

Worker is running...
Worker is running...
Worker is running...

Exception in thread Thread-9 (worker):
Traceback (most recent call last):
  File "/Users/adivekar/miniconda3/envs/synthesizrr/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "/Users/adivekar/miniconda3/envs/synthesizrr/lib/python3.11/site-packages/ipykernel/ipkernel.py", line 766, in run_closure
    _threading_Thread_run(self)
  File "/Users/adivekar/miniconda3/envs/synthesizrr/lib/python3.11/threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "/var/folders/0b/h2z5fys10h5cxlgh2tqf1y840000gr/T/ipykernel_16005/395068026.py", line 5, in worker
synthergent.base.util.concurrency.ThreadKilledSystemException

In [10]:
# Example: Create and terminate a thread
def worker():
    for _ in range(10):
        print("Worker running...")
        time.sleep(1)

# Create a thread
t = threading.Thread(target=worker)
t.start()

# Let the thread run for a while
time.sleep(3)

# Kill the thread
kill_thread(t.ident)

# Wait for the thread to terminate
t.join()

Worker running...
Worker running...
Worker running...

Exception in thread Thread-9 (worker):
Traceback (most recent call last):
  File "/Users/adivekar/miniconda3/envs/synthesizrr/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "/Users/adivekar/miniconda3/envs/synthesizrr/lib/python3.11/site-packages/ipykernel/ipkernel.py", line 766, in run_closure
    _threading_Thread_run(self)
  File "/Users/adivekar/miniconda3/envs/synthesizrr/lib/python3.11/threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "/var/folders/0b/h2z5fys10h5cxlgh2tqf1y840000gr/T/ipykernel_2123/2899910319.py", line 5, in worker
synthergent.base.util.concurrency.ThreadKillException

In [1]:
import sys
from pathlib import Path
HOME_DIR = Path.home()
SYNTHERGENT_DIR = HOME_DIR / 'workplace' / 'synthesizrr' / 'src' 
sys.path.insert(-2, str(SYNTHERGENT_DIR))

from pprint import pprint
import ray
import copy, json, yaml, os, io, gzip, bz2, lzma, ray, gc, glob
os.environ['DISABLE_DEFAULT_TRACKER'] = 'True'
import dask.dataframe as dd
import pandas as pd
from ray.util.dask import ray_dask_get, enable_dask_on_ray, disable_dask_on_ray
from bokeh.palettes import viridis
from synthergent.base.util import *
from synthergent.base.data import *
from synthergent.base.metric.classification_metrics import *
from synthergent.base.framework import *
from synthergent.base.framework.task.classification import _normalize_label
import synthergent.base.algorithm

import hvplot.pandas
import holoviews as hv
import plotly.express as px
import plotly.io as pio
from IPython.display import display
from bokeh.palettes import Spectral, Set2, Set3

pio.templates.default = 'plotly_white'
hvplot.extension('bokeh')
# hvplot.extension('plotly')

pio.renderers.default='iframe'


from synthergent import Synthergent, Cleaner
import cleaners  ## Importing these registers all the cleaners

/var/folders/0b/h2z5fys10h5cxlgh2tqf1y840000gr/T/ipykernel_16796/483508581.py:11: DeprecationWarning: The current Dask DataFrame implementation is deprecated.
In a future release, Dask DataFrame will use new implementation that
contains several improvements including a logical query planning.
The user-facing DataFrame API will remain unchanged.

The new implementation is already available and can be enabled by
installing the dask-expr library:

    $ pip install dask-expr

and turning the query planning option on:

    >>> import dask
    >>> dask.config.set({'dataframe.query-planning': True})
    >>> import dask.dataframe as dd

API documentation for the new implementation is available at
https://docs.dask.org/en/stable/dask-expr-api.html

Any feedback can be reported on the Dask issue tracker
https://github.com/dask/dask/issues

  import dask.dataframe as dd

In [2]:
_data = pd.DataFrame([
    dict(idx=idx, generations='ha')
    for idx in range(int(10e6))
])

In [3]:
_data

             idx generations
0              0          ha
1              1          ha
2              2          ha
3              3          ha
4              4          ha
...          ...         ...
9999995  9999995          ha
9999996  9999996          ha
9999997  9999997          ha
9999998  9999998          ha
9999999  9999999          ha

[10000000 rows x 2 columns]

In [4]:
cleaning_chain = Synthergent.of(
    Cleaner.of('AddSuffix', params={'suffix': ' lol', 'reps': 1}),
    Cleaner.of('AddSuffix', params={'suffix': ' lol', 'reps': 1}),
    Cleaner.of('AddSuffix', params={'suffix': ' lol', 'reps': 1}),
)
_exn = cleaning_chain(
    data=_data,
    scaling=dict(
        parallelize='sync',
        max_workers=2,
        batch_size=30e3,
    ),
    return_exn=True,
    # save=dict(path='~/ray/lol/', format='parquet'),
)
_exn.outputs['data']

Synthergent:   0%|          | 0/3 [00:00<?, ?step/s]

             idx     generations
0              0  ha lol lol lol
1              1  ha lol lol lol
2              2  ha lol lol lol
3              3  ha lol lol lol
4              4  ha lol lol lol
...          ...             ...
9999995  9999995  ha lol lol lol
9999996  9999996  ha lol lol lol
9999997  9999997  ha lol lol lol
9999998  9999998  ha lol lol lol
9999999  9999999  ha lol lol lol

[10000000 rows x 2 columns]

In [5]:
cleaning_chain = Synthergent.of(
    Cleaner.of('AddSuffix', params={'suffix': ', lol'}),
    ParallelMap.of(
        Cleaner.of('AddSuffix', params={'suffix': 'a', 'reps': 100}),
        Cleaner.of('AddSuffix', params={'suffix': 'b', 'reps': 100}),
        Cleaner.of('AddSuffix', params={'suffix': 'c', 'reps': 100}),
        combine='dict',
        parallelize='threads',
    ),
)
_exn = cleaning_chain(
    data=_data,
    scaling=dict(
        parallelize='processes',
        max_workers=5,
        batch_size=30e3,
    ),
    return_exn=True,
    # save=dict(path='~/ray/lol/', format='parquet'),
)
_exn.outputs['parallel_map_results']

Synthergent:   0%|          | 0/2 [00:00<?, ?step/s]

(Synthergent: Step 2/2):   0%|          | 0/3 [00:00<?, ?step/s]

{0: {'data':              idx                                        generations
  0              0  ha, lolaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa...
  1              1  ha, lolaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa...
  2              2  ha, lolaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa...
  3              3  ha, lolaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa...
  4              4  ha, lolaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa...
  ...          ...                                                ...
  9999995  9999995  ha, lolaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa...
  9999996  9999996  ha, lolaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa...
  9999997  9999997  ha, lolaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa...
  9999998  9999998  ha, lolaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa...
  9999999  9999999  ha, lolaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa...

  [10000000 rows x 2 columns]},
 1: {'data':              idx                                        generations
  0              0  ha, lolbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb...
  1              1  ha, lolbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb...
  2              2  ha, lolbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb...
  3              3  ha, lolbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb...
  4              4  ha, lolbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb...
  ...          ...                                                ...
  9999995  9999995  ha, lolbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb...
  9999996  9999996  ha, lolbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb...
  9999997  9999997  ha, lolbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb...
  9999998  9999998  ha, lolbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb...
  9999999  9999999  ha, lolbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb...

  [10000000 rows x 2 columns]},
 2: {'data':              idx                                        generations
  0              0  ha, lolccccccccccccccccccccccccccccccccccccccc...
  1              1  ha, lolccccccccccccccccccccccccccccccccccccccc...
  2              2  ha, lolccccccccccccccccccccccccccccccccccccccc...
  3              3  ha, lolccccccccccccccccccccccccccccccccccccccc...
  4              4  ha, lolccccccccccccccccccccccccccccccccccccccc...
  ...          ...                                                ...
  9999995  9999995  ha, lolccccccccccccccccccccccccccccccccccccccc...
  9999996  9999996  ha, lolccccccccccccccccccccccccccccccccccccccc...
  9999997  9999997  ha, lolccccccccccccccccccccccccccccccccccccccc...
  9999998  9999998  ha, lolccccccccccccccccccccccccccccccccccccccc...
  9999999  9999999  ha, lolccccccccccccccccccccccccccccccccccccccc...

  [10000000 rows x 2 columns]}}

In [13]:
_cleaned_data = cleaning_chain(
    data=_data,
    scaling=dict(
        parallelize='processes',
        max_workers=5,
    ),
    return_exn=False,
    # save=dict(path='~/ray/lol/', format='parquet'),
)

Synthergent:   0%|          | 0/3 [00:00<?, ?step/s]

In [14]:
_cleaned_data

             idx     generations
0              0  ha lol lol lol
1              1  ha lol lol lol
2              2  ha lol lol lol
3              3  ha lol lol lol
4              4  ha lol lol lol
...          ...             ...
9999995  9999995  ha lol lol lol
9999996  9999996  ha lol lol lol
9999997  9999997  ha lol lol lol
9999998  9999998  ha lol lol lol
9999999  9999999  ha lol lol lol

[10000000 rows x 2 columns]

In [1]:
import sys
from pathlib import Path
HOME_DIR = Path.home()
SYNTHERGENT_DIR = HOME_DIR / 'workplace' / 'synthesizrr' / 'src' 
sys.path.insert(-2, str(SYNTHERGENT_DIR))

from pprint import pprint
import ray
import copy, json, yaml, os, io, gzip, bz2, lzma, ray, gc, glob
os.environ['DISABLE_DEFAULT_TRACKER'] = 'True'
import dask.dataframe as dd
import pandas as pd
from ray.util.dask import ray_dask_get, enable_dask_on_ray, disable_dask_on_ray
from bokeh.palettes import viridis
from synthergent.base.util import *
from synthergent.base.data import *
from synthergent.base.metric.classification_metrics import *
from synthergent.base.framework import *
from synthergent.base.framework.task.classification import _normalize_label
import synthergent.base.algorithm

import hvplot.pandas
import holoviews as hv
import plotly.express as px
import plotly.io as pio
from IPython.display import display
from bokeh.palettes import Spectral, Set2, Set3

pio.templates.default = 'plotly_white'
hvplot.extension('bokeh')
# hvplot.extension('plotly')

pio.renderers.default='iframe'

/var/folders/0b/h2z5fys10h5cxlgh2tqf1y840000gr/T/ipykernel_13751/1974000823.py:11: DeprecationWarning: The current Dask DataFrame implementation is deprecated.
In a future release, Dask DataFrame will use new implementation that
contains several improvements including a logical query planning.
The user-facing DataFrame API will remain unchanged.

The new implementation is already available and can be enabled by
installing the dask-expr library:

    $ pip install dask-expr

and turning the query planning option on:

    >>> import dask
    >>> dask.config.set({'dataframe.query-planning': True})
    >>> import dask.dataframe as dd

API documentation for the new implementation is available at
https://docs.dask.org/en/stable/dask-expr-api.html

Any feedback can be reported on the Dask issue tracker
https://github.com/dask/dask/issues

  import dask.dataframe as dd

In [2]:
from synthergent import Synthergent, Cleaner
import cleaners  ## Importing these registers all the cleaners

In [3]:
_data = pd.DataFrame([
    dict(idx=idx, generations='ha')
    for idx in range(int(10e6))
])

In [4]:
addlol = Cleaner.of('AddLol', params=dict(reps=20))

In [15]:
executor = ActorPoolExecutor(max_workers=5)
futs = []
with Timer():
    for batch in ScalableDataFrame.of(_data).stream(batch_size=100e3):
        futs.append(
            executor.submit(
                addlol.clean,
                batch,
            )
        )
_ = ScalableDataFrame.concat(accumulate(futs, pbar=True))
with Timer():
    executor.shutdown()

Started at 2024-12-13T11:30:08.970312+05:30...
...completed in 2.12 seconds.

Collecting:  11%|#1        | 11/100 [00:00<?, ?item/s]

Started at 2024-12-13T11:30:15.672699+05:30...
...completed in 154.66 milliseconds.

In [14]:
_

Pandas DataFrame with 10000000 row(s) and 2 column(s):
Columns:['idx', 'generations']:
Data:
             idx                                        generations
0              0  ha lol lol lol lol lol lol lol lol lol lol lol...
1              1  ha lol lol lol lol lol lol lol lol lol lol lol...
2              2  ha lol lol lol lol lol lol lol lol lol lol lol...
3              3  ha lol lol lol lol lol lol lol lol lol lol lol...
4              4  ha lol lol lol lol lol lol lol lol lol lol lol...
...          ...                                                ...
9999995  9999995  ha lol lol lol lol lol lol lol lol lol lol lol...
9999996  9999996  ha lol lol lol lol lol lol lol lol lol lol lol...
9999997  9999997  ha lol lol lol lol lol lol lol lol lol lol lol...
9999998  9999998  ha lol lol lol lol lol lol lol lol lol lol lol...
9999999  9999999  ha lol lol lol lol lol lol lol lol lol lol lol...

[10000000 rows x 2 columns]

In [1]:
import sys
from pathlib import Path
HOME_DIR = Path.home()
SYNTHERGENT_DIR = HOME_DIR / 'workplace' / 'synthesizrr' / 'src' 
sys.path.insert(-2, str(SYNTHERGENT_DIR))

from pprint import pprint
import ray
import copy, json, yaml, os, io, gzip, bz2, lzma, ray, gc, glob
os.environ['DISABLE_DEFAULT_TRACKER'] = 'True'
import dask.dataframe as dd
import pandas as pd
from ray.util.dask import ray_dask_get, enable_dask_on_ray, disable_dask_on_ray
from bokeh.palettes import viridis
from synthergent.base.util import *
from synthergent.base.data import *
from synthergent.base.metric.classification_metrics import *
from synthergent.base.framework import *
from synthergent.base.framework.task.classification import _normalize_label
import synthergent.base.algorithm

import hvplot.pandas
import holoviews as hv
import plotly.express as px
import plotly.io as pio
from IPython.display import display
from bokeh.palettes import Spectral, Set2, Set3

pio.templates.default = 'plotly_white'
hvplot.extension('bokeh')
# hvplot.extension('plotly')

pio.renderers.default='iframe'

/var/folders/0b/h2z5fys10h5cxlgh2tqf1y840000gr/T/ipykernel_6157/1974000823.py:11: DeprecationWarning: The current Dask DataFrame implementation is deprecated.
In a future release, Dask DataFrame will use new implementation that
contains several improvements including a logical query planning.
The user-facing DataFrame API will remain unchanged.

The new implementation is already available and can be enabled by
installing the dask-expr library:

    $ pip install dask-expr

and turning the query planning option on:

    >>> import dask
    >>> dask.config.set({'dataframe.query-planning': True})
    >>> import dask.dataframe as dd

API documentation for the new implementation is available at
https://docs.dask.org/en/stable/dask-expr-api.html

Any feedback can be reported on the Dask issue tracker
https://github.com/dask/dask/issues

  import dask.dataframe as dd

In [2]:
# import importlib
# import actor
# from actor import *
# importlib.reload(actor)
# import actor
# from actor import *

In [3]:
@actor
class CounterActor:
    def __init__(self, start_value=0):
        self.count = start_value

    def increment(self, value=1):
        self.count += value
        return self.count

    def get_count(self):
        return self.count

    def reset(self):
        self.count = 0
        return self.count

    def count_to(self, i):
        count = self.count
        for _ in range(int(i)):
            count += 1
        return count

In [4]:
class LolzActor(Actor):
    def __init__(self):
        self.name = 'lol'

    def set_name(self, name: str):
        self.name += name
        
    def get_name(self):
        return self.name

In [5]:
_act = LolzActor.remote()
for _ in range(5):
    _act.set_name.remote('lol')
    print(_act.get_name.remote().result())

lollol
lollollol
lollollollol
lollollollollol
lollollollollollol

In [9]:
with Timer():
    print(_act.submitted())

Started at 2024-12-13T11:00:13.420881+05:30...
10
...completed in 210.12 microseconds.

In [6]:
_act = LolzActor.options(num_cpus=1).remote()
for _ in range(5):
    _act.set_name.remote('lol')
    print(_act.get_name.remote().result())

/Users/adivekar/workplace/synthesizrr/src/synthergent/base/util/concurrency.py:514: UserWarning:

The process-based Actor "LolzActor" cannot use .options(); this call will be ignored.

lollol
lollollol
lollollollol
lollollollollol
lollollollollollol

In [7]:
with Timer():
    actor1 = CounterActor.remote(start_value=10)
with Timer():
    actor2 = CounterActor.remote(start_value=100)
with Timer():
    actor3 = CounterActor.remote(start_value=1000)
with Timer():
    actor4 = CounterActor.remote(start_value=10000)

Started at 2024-12-12T20:10:51.030451+05:30...
...completed in 24.66 milliseconds.
Started at 2024-12-12T20:10:51.060791+05:30...
...completed in 24.36 milliseconds.
Started at 2024-12-12T20:10:51.091495+05:30...
...completed in 187.23 milliseconds.
Started at 2024-12-12T20:10:51.285422+05:30...
...completed in 31.65 milliseconds.

In [8]:
# Calls return Futures immediately
f1 = actor1.increment.remote(10)
f2 = actor2.increment.remote(50)
f3 = actor1.get_count.remote()
f4 = actor2.get_count.remote()

# Wait for results
print("actor1 increment by 10:", f1.result())  # Should be 20
print("actor2 increment by 50:", f2.result())  # Should be 150
print("actor1 count:", f3.result())            # Should be 20
print("actor2 count:", f4.result())            # Should be 150

# # Shutdown actors
# actor1.stop()
# actor2.stop()

actor1 increment by 10: 20
actor2 increment by 50: 150
actor1 count: 20
actor2 count: 150

In [9]:
with Timer():
    print(accumulate(
        [
            actor1.count_to.remote(int(300e6)),
            actor2.count_to.remote(int(300e6)),
            actor3.count_to.remote(int(300e6)),
            actor4.count_to.remote(int(300e6)),
        ],
        pbar=True,
    ))

Started at 2024-12-12T20:10:51.382533+05:30...

Collecting:   0%|          | 0/4 [00:00<?, ?item/s]

[300000020, 300000150, 300001000, 300010000]
...completed in 6.73 seconds.

In [10]:
with Timer():
    print(accumulate(
        [
            actor1.count_to.options(num_cpus=10).remote(int(300e6)),
            actor2.count_to.options(num_cpus=10).remote(int(300e6)),
            actor3.count_to.options(num_cpus=10).remote(int(300e6)),
            actor4.count_to.options(num_cpus=10).remote(int(300e6)),
        ],
        pbar=True,
    ))

Started at 2024-12-12T20:10:58.119560+05:30...

/Users/adivekar/workplace/synthesizrr/src/synthergent/base/util/concurrency.py:465: UserWarning:

The process-based Actor "CounterActor" cannot use .options(); this call will be ignored.

Collecting:   0%|          | 0/4 [00:00<?, ?item/s]

[300000020, 300000150, 300001000, 300010000]
...completed in 6.23 seconds.

In [11]:
with Timer():
    print(actor1.count_to.remote(int(300e6)).result())
    print(actor2.count_to.remote(int(300e6)).result())
    print(actor3.count_to.remote(int(300e6)).result())
    print(actor4.count_to.remote(int(300e6)).result())

Started at 2024-12-12T20:11:04.351819+05:30...
300000020
300000150
300001000
300010000
...completed in 23.9 seconds.

In [ ]:
import joblib

In [ ]:
from concurrent.futures import Executor, Future, ThreadPoolExecutor
from joblib import Parallel, delayed

class JoblibExecutor(Executor):
    def __init__(self, max_workers=None, backend='loky', verbose=0):
        """
        A simple executor-like class that uses joblib.Parallel under the hood.
        
        Parameters
        ----------
        max_workers : int, optional
            The number of jobs to run in parallel (default: all CPUs).
        backend : str, optional
            The parallelization backend to use (e.g. 'loky', 'multiprocessing', 'threading').
            If None, joblib chooses the best available default.
        verbose : int, optional
            The verbosity level for joblib.Parallel.
        """
        self.max_workers = max_workers
        self.backend = backend
        self.verbose = verbose
        self._shutdown = False
        # Use a thread pool to handle running parallel tasks asynchronously
        self._thread_pool = ThreadPoolExecutor(max_workers=max_workers+1)

    def submit(self, fn, *args, **kwargs):
        """
        Schedules the fn(*args, **kwargs) to be executed and returns a Future.
        """
        if self._shutdown:
            raise RuntimeError("Cannot schedule new futures after shutdown.")

        future = Future()

        def run_task():
            try:
                # We run a single task via Parallel, which returns a list of results.
                # Since we're only giving it one function call, we get a single-result list.
                results = Parallel(n_jobs=self.max_workers, backend=self.backend, verbose=self.verbose)(
                    [delayed(fn)(*args, **kwargs)]
                )
                future.set_result(results[0])
            except Exception as e:
                future.set_exception(e)

        # Submit the parallel run to the thread pool so that it doesn't block
        self._thread_pool.submit(run_task)
        return future

    def shutdown(self, wait=True):
        """
        Clean up the executor. If wait=True, wait for all pending futures to finish.
        """
        self._shutdown = True
        self._thread_pool.shutdown(wait=wait)

    def map(self, fn, *iterables, timeout=None, chunksize=1):
        """
        An optional map method, similar to ProcessPoolExecutor.map, but runs all at once.
        
        Note: This method is synchronous. It runs the entire mapping at once using Parallel.
        """
        if self._shutdown:
            raise RuntimeError("Cannot schedule new futures after shutdown.")

        # Prepare the tasks
        # joblib Parallel likes a list of delayed calls
        tasks = (delayed(fn)(*args) for args in zip(*iterables))
        results = Parallel(n_jobs=self.max_workers, backend=self.backend, verbose=self.verbose)(tasks)
        return results

In [ ]:
_executor = JoblibExecutor(max_workers=6)

In [ ]:
def lol(i, ob):
    for _ in range(int(100e6)): 
        i += 1
    return f'Lolz: {i}'

futs = []
for _ in range(30):
    futs.append(_executor.submit(
        lol,
        _,
        AddLol.of()
    ))
accumulate(futs, pbar=True)